### ISSUE TITLE
fedex Track API has a new JSON schema, needs to be upgraded.

### ISSUE THREAD

**Issue by xqiu** [ShipStream/fedex-rest-php-sdk#3]
If not upgraded, current Track API is not usable, due to holdAtLocation's schema changed from LocationDetail to LocationDetail11

**Comment by colinmollenhour** [comment]
@jlevers Can you take a look at this and submit a proper fix for the schema change, please?

**Comment by jlevers** [comment]
Will do!

**Comment by jlevers** [comment]
@xqiu looking into this now – where are you seeing that schema change? I just re-downloaded the Track V1 JSON schema, and don't see any differences. I'm definitely happy to override FedEx's official OpenAPI spec if you're seeing the `locationType` attribute of the `holdAtLocation` schema coming back empty, but as far as I can tell their spec does say that that field is required (I'm looking at their schema [here](https://developer.fedex.com/wirc/json/api_groups/Track/TCN-Resource.json)).

**Comment by xqiu** [comment]
@jlevers I went to https://developer.fedex.com/api/en-us/catalog/track/v1/docs.html , click on Download JSON Schema, I get the following:
[track.json](https://github.com/user-attachments/files/17788155/track.json)

Which is different with the json schema on https://[developer.fedex.com/wirc/json/api_groups/Track/TCN-Resource.json](https://developer.fedex.com/wirc/json/api_groups/Track/TCN-Resource.json)

Seems like FedEx did not update their JSON file?

Perplexity.ai said:
The first URL (https://developer.fedex.com/wirc/json/api_groups/Track/TCN-Resource.json) seems to be a specific JSON resource for TCN (Transportation Control Number) tracking.
The second URL (https://developer.fedex.com/api/en-us/catalog/track/v1/docs.html) is the general documentation for the FedEx Track API v1.

**Comment by jlevers** [comment]
The JSON Schema link on the documentation page is pretty annoying to download programmatically (it's a `blob:` link), which is why I'm downloading the individual resource files that the documentation page loads and composing them into a single schema file in the generator. Until now it's seemed that my manually composed schema file matched the FedEx one well enough, but now that's changed.

I'm going to email them and ask them if there's an easier-to-use link to the final schema somewhere, but in the meantime I'll override this library's internal `track.json` schema to fix this bug.

**Comment by jlevers** [comment]
@xqiu can you change your `composer.json` to point at `dev-3-track-api-location-type-optional` instead of `^1.1`, and confirm that your issue is resolved? You may have to add this to your `composer.json` temporarily, to be able to install the package from a branch:

```json
{
    "minimum-stability": "dev"
}
```

**Comment by xqiu** [comment]
Confirmed the issue is solved with the change in dev-3-track-api-location-type-optional branch.  Thanks!

**Comment by jlevers** [comment]
Sweet! I just released the fix in `v1.1.2`.
